
name: PHPUnit
on:
  push:
    branches: ['dev']
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
      mysql:
        image: mysql:'9.0.1'
        env:
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_ALLOW_EMPTY_PASSWORD:   true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
       matrix:
        os: [ubuntu-24.04]
        php: [8.3]
        phpunit: [12.0.2]
        include:
           - testbench: 9.9.0
        dependencies:
          - "locked"
          - "lowest"
          - "highest"
        experimental:
          - false

    name: ${{ matrix.os }} - ${{ matrix.php }} - ${{ matrix.phpunit }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: nanasess/setup-php@v4.0.2

      - name: Install composer dependencies
        uses: ramsey/composer-install@2.3.1
        with:
          composer-options: "--prefer-dist --no-interaction"

      - name: Unit Test
        run: |
          "'/vendor/bin/phpunit' --testsuite Unit | php"
